services:
  - type: web
    name: crypto-price-websocket
    env: docker
    plan: free
    region: ohio
    # If you connect the root of your repo, keep this rootDir as 'stackera'.
    # If you connect just the 'stackera' folder, delete this line.
    rootDir: stackera
    envVars:
      - key: PORT
        value: 10000
      - key: MAX_CLIENTS
        value: 100
      - key: TRADING_PAIRS
        value: btcusdt,ethusdt,bnbusdt
      - key: RECONNECT_DELAY_MS
        value: 5000
      - key: BINANCE_WS_BASE_URL
        value: wss://data-stream.binance.com/ws
